### ISSUE TITLE
Potential bug when using 'cutoff'-functionality

### ISSUE THREAD

**Issue by WolfXeHD** [valdezt/sigfig#9]
Hi @valdezt , hi @MikeBusuttil ,

this is a great package many thanks for it! I think I might have discovered a bug. If this is not the case, please tell me why it is a feature:

Say we have:
```
import sigfig

value = 0.9656333507365017
uncert = 0.548083313468262

# then I call
rounded_result = sigfig.round(value, uncert, cutoff=19)
print(rounded_result) # prints '1.0 ± 0.6'
```

Another example:

```
import sigfig

value = 0.9656333507365017
uncert = 0.544083313468262

# notice the difference in the 3rd digit of the uncert variable

# then I call
rounded_result = sigfig.round(value, uncert, cutoff=19)
print(rounded_result) # prints '1.0 ± 0.5'
```

From a quick inspection of your code, I think it stems from this [line](https://github.com/valdezt/sigfig/blob/66155e0837799fecc391d38a87caa1ba977f3191/sigfig/sigfig.py#L587) where `given['uncertainty']` is then the output of [this line](https://github.com/valdezt/sigfig/blob/66155e0837799fecc391d38a87caa1ba977f3191/sigfig/sigfig.py#L584). I guess internally, `given['uncertainty']` is overwritten to be the rounded number. But I am unsure if this is the behavior that you actually want?

Or is this intended and I overlooked something in your documentation?

Cheers,
Tim

**Comment by MikeBusuttil** [comment]
Thanks Tim, good catch, that's a bug.  I'll work on a fix and let you know when its merged.

**Comment by MikeBusuttil** [comment]
Hey Tim, the fix has been merged.  You can update `sigfig` by running `pip3 install sigfig -U` in your terminal.  Give it a whirl and let me know if that solves your issue.  Thanks again for bringing that to our attention.
Regards,
-Mike

**Comment by WolfXeHD** [comment]
Hi Mike,
the example that I posted above seems to be fixed. But I wonder why there is no update to the repo here? I would be interested in how you fixed it.

I am also wondering if one should use a continuous integration for the tests (and extend the tests). This is a prime example which one could have spotted with functioning unittests.
On another note: Can you tell me how to run the tests locally?
Cheers,
Tim

**Comment by MikeBusuttil** [comment]
The main repo is at https://github.com/drakegroup/sigfig

CI test integration would of course be best practice.  However, the test case for your special example didn't exist until you raised it.  We have unit tests for most known cases and edge cases, feel free to suggest some more.

To run test locally:

- clone the repo at https://github.com/drakegroup/sigfig
- navigate to the `test` directory
- run `python3 test.py`

**Comment by WolfXeHD** [comment]
Great! Thanks for the clarification!
